// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZENITH.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string UserId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string AddressLine { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ApplicationUser User { get; set; }
}
