// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZENITH.Models;

public partial class CartItem
{
    public int CartId { get; set; }

    public string UserId { get; set; }

    public int VariantId { get; set; }

    public int Quantity { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ApplicationUser User { get; set; }
    public virtual ProductVariant ProductVariant { get; set; }
}
