// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZENITH.Models;

public partial class InventoryLog
{
    public int LogId { get; set; }

    public int VariantId { get; set; }

    public string UserId { get; set; }

    public string ActionType { get; set; }

    public int QuantityChange { get; set; }

    public int QuantityAfter { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ApplicationUser User { get; set; }
    public virtual ProductVariant ProductVariant { get; set; }
}
