// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZENITH.Models;

public partial class OrderStatusHistory
{
    public int HistoryId { get; set; }

    public int OrderId { get; set; }

    public string UserId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ApplicationUser User { get; set; }
}
