﻿// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ZENITH.AppData;

#nullable disable

namespace ZENITH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112090031_ReviewCommentUnicode2")]
    partial class ReviewCommentUnicode2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}

